# Use an official Nginx image
FROM nginx:alpine


# Copy your front-end code into the container
COPY ./assets /usr/share/nginx/html/assets

#Copy the images folder to the correct directory in the container
COPY ./images /usr/share/nginx/html/images

#Copy the nginx.conf file to the nginx configuration directory
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80
