version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "EpsilonGamma24"
  website:
    build: .
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - '8080:8080'