events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html; #Set the root directory
    index assets/html/index.html; #Set the default index page

    location / {
       #try_files $uri $uri/ /assets/html/index.html;
       proxy_pass http://172.18.0.4:3000; 
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection 'upgrade';
       proxy_set_header Host $host;
       proxy_cache_bypass $http_upgrade;
    }

     # Reverse proxy to backend Express app
      location /assets/ {
        proxy_pass http://172.18.0.4:3000;  # Forward static files to Express
    }

      location /images/ {
        proxy_pass http://172.18.0.4:3000;  # Forward image requests to Express
    }
      
  }
}
