# Use Node.js image
FROM node:16

# Set the working directory
WORKDIR /MuGammaWebsite/backend

# Copy package.json and install dependencies
COPY backend/package*.json ./

# Copy your front-end code into the container
COPY ./assets /MuGammaWebsite/assets

#Copy the images folder to the correct directory in the container
COPY ./images /MuGammaWebsite/images

#Copy the nginx.conf file to the nginx configuration directory
COPY ./nginx.conf /etc/nginx/nginx.conf

#Install dependencies 
RUN npm install



# Copy the rest of the backend code into the container
COPY backend/ ./



# Expose the port your backend runs on
EXPOSE 3000

# Download the docker-compose-wait binary
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait

# Make it executable
RUN chmod +x /wait


# Command to run the backend server
CMD ["sh", "-c", "/wait && node index.js"]
