events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html; #Set the root directory
    index assets/html/index.html; #Set the default index page

    location / {
        try_files $uri $uri/ /assets/html/index.html;
    }

    location /assets/html/ {
        alias /usr/share/nginx/html/assets/html/;
    }

    location /css {
        alias /usr/share/nginx/html/assets/css;
    }

    location /images {
        alias /usr/share/nginx/html/images;
    }

    location /js {
        alias /usr/share/nginx/html/assets/js;
    }
  }
}
