# Use Node.js image
FROM node:16

# Set the working directory
WORKDIR /MuGammaWebsite-dev/backend

# Copy package.json and install dependencies
COPY backend/package*.json ./

#Install dependencies 
RUN npm install



# Copy the rest of the backend code into the container
COPY backend/ ./



# Expose the port your backend runs on
EXPOSE 3000

# Command to run the backend server
CMD ["node", "index.js"]
